/*




*/

drop table cards;
drop table transactions;
drop table super_users;
drop table transfers;
drop table deposits_and_withdrawls;
drop table errors;
drop table accounts;
drop table users;

--SEQUENCES
DROP SEQUENCE ACCOUNT_SEQ;

DROP SEQUENCE CARD_NUMBER_SEQUENCE;

DROP SEQUENCE CARD_SEQ;

DROP SEQUENCE DEPOSIT_WITHDRAWL_SEQ;

DROP SEQUENCE ERROR_SEQ;

DROP SEQUENCE SUPER_USER_SEQ;

DROP SEQUENCE TRANSACTION_SEQ;

DROP SEQUENCE TRANSFER_SEQ;

DROP SEQUENCE USER_SEQ;

--procedures

DROP PROCEDURE ADD_ACCOUNT;
DROP PROCEDURE ADD_CARD;
DROP PROCEDURE ADD_DEPOSIT_WITHDRAWL;
DROP PROCEDURE ADD_ERROR;
DROP PROCEDURE ADD_SUPER_USER;
DROP PROCEDURE ADD_TRANSACTION;
DROP PROCEDURE ADD_TRANSFER;
DROP PROCEDURE ADD_USER;
DROP PROCEDURE REMOVE_ACCOUNT;
DROP PROCEDURE REMOVE_CARD;
DROP PROCEDURE REMOVE_DEPOSIT_WITHDRAWL;
DROP PROCEDURE REMOVE_ERROR;
DROP PROCEDURE REMOVE_SUPER_USER;
DROP PROCEDURE REMOVE_TRANSACTION;
DROP PROCEDURE REMOVE_TRANSFER;
DROP PROCEDURE REMOVE_USER;
DROP PROCEDURE SIGN_IN_SUPER_USER;
DROP PROCEDURE SIGN_IN_USER;
DROP PROCEDURE UPDATE_ACCOUNT_BALANCE;
DROP PROCEDURE UPDATE_FIRST_NAME;
DROP PROCEDURE UPDATE_LAST_NAME;
DROP PROCEDURE UPDATE_PASSWORD;
DROP PROCEDURE UPDATE_PHONE_NUMBER;
DROP PROCEDURE UPDATE_SUPER_PASSWORD;
DROP PROCEDURE UPDATE_SUPER_USERNAME;
DROP PROCEDURE UPDATE_USERNAME;
